#!/bin/bash

case $1 in
    lint )  sudo make lint
            ;;

    debug ) sudo make interface
            sudo ./node_modules/.bin/nodemon --watch . --ext js --signal SIGINT --exec "sudo node -e 'require(`./main`)();' -- -d"
            ;;

    build ) sudo make portal
            ;;

    clean ) sudo make clean
            ;;

    * )     ARGUMENTS="$ARGUMENTS $1"
            ;;
esac
