#!/bin/bash

version() {
    echo `node -e 'console.log(require("./package.json").version)'`
}

debug() {
    sudo make interface
    sudo ./node_modules/.bin/nodemon --watch . --ext js --signal SIGINT --exec "sudo node -e 'require(`./main`)();' -- -d"
}

include() {
    case $1 in
        stable )    reprepro -b ../repo/debian includedeb bleeding builds/hbs-portal-$2-hoobs-$3.deb
                    reprepro -b ../repo/debian includedeb edge builds/hbs-portal-$2-hoobs-$3.deb
                    reprepro -b ../repo/debian includedeb stable builds/hbs-portal-$2-hoobs-$3.deb
                    ;;

        edge )      reprepro -b ../repo/debian includedeb bleeding builds/hbs-portal-$2-hoobs-$3.deb
                    reprepro -b ../repo/debian includedeb edge builds/hbs-portal-$2-hoobs-$3.deb
                    ;;

        bleeding )  reprepro -b ../repo/debian includedeb bleeding builds/hbs-portal-$2-hoobs-$3.deb
                    ;;

        * )         ;;
    esac
}

publish() {
    current=$(version)

    case $1 in
        stable )    include "stable" "$current" "all"
                    ;;

        edge )      include "edge" "$current" "all"
                    ;;

        bleeding )  include "bleeding" "$current" "all"
                    ;;

        * )         ;;
    esac
}

list() {
    case $1 in
        stable )    reprepro -b ../repo/debian list stable
                    ;;

        edge )      reprepro -b ../repo/debian list edge
                    ;;

        bleeding )  reprepro -b ../repo/debian list bleeding
                    ;;

        * )         reprepro -b ../repo/debian list stable
                    reprepro -b ../repo/debian list edge
                    reprepro -b ../repo/debian list bleeding
                    ;;
    esac
}

case $1 in
    version )  version
               ;;

    lint )     make lint
               ;;

    debug )    debug
               ;;

    build )    make portal
               ;;

    rebuild )  make clean
               make portal
               ;;

    publish )  publish $2
               ;;

    list )     list $2
               ;;

    clean )    make clean
               ;;

    * )        ;;
esac
