#!/bin/bash

version() {
    echo `node -e 'console.log(require("./package.json").version)'`
}

debug() {
    rm -fR ./interface/*

    ./node_modules/.bin/vue-cli-service lint
	./node_modules/.bin/vue-cli-service build --modern

    sudo ./debug -d
}

include() {
    if [[ -f "../repo/debian/pool/main/h/hbs-portal/hbs-portal_$2_$3.deb" ]]; then
        echo "$2-$3 already published"
    else
        reprepro -b ../repo/debian includedeb $1 builds/hbs-portal-$2-hoobs-$3.deb
    fi
}

publish() {
    current=$(version)

    case $1 in
        stable )
            include "stable" "$current" "all"
            ;;

        edge )
            include "edge" "$current" "all"
            ;;

        bleeding )
            include "bleeding" "$current" "all"
            ;;

        list )
            list $2
            ;;
    esac
}

list() {
    case $1 in
        stable )
            reprepro -b ../repo/debian list stable hbs-portal
            ;;

        edge )
            reprepro -b ../repo/debian list edge hbs-portal
            ;;

        bleeding )
            reprepro -b ../repo/debian list bleeding hbs-portal
            ;;

        * )
            reprepro -b ../repo/debian list stable hbs-portal
            reprepro -b ../repo/debian list edge hbs-portal
            reprepro -b ../repo/debian list bleeding hbs-portal
            ;;
    esac
}

case $1 in
    version ) 
        version
        ;;

    lint )
        make lint
        ;;

    debug )
        debug
        ;;

    build )
        make portal
        ;;

    publish )
        shift

        publish $@
        ;;

    clean )
        make clean
        ;;
esac
